In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('last_satis.csv')

In [7]:
df.columns = df.columns.str.strip()

In [9]:
df

,Unnamed: 0,Tarix,Mağaza,Kart_nomresi,Transaksiya_id,Məhsul_nomresi,Məhsul_adi,Məhsul sayi,Ümumi satış
0,0,43390,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,1,43599,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3
2,2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9
3,3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0
4,4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8
...,...,...,...,...,...,...,...,...,...
199995,199995,43474,212,212091,210993,114,Kettle Sensations Siracha Lime 150g,2,9.2
199996,199996,43494,212,212091,210994,106,Natural ChipCo Hony Soy Chckn175g,2,6.0
199997,199997,43571,212,212091,210995,61,Smiths Crinkle Cut Chips Chicken 170g,2,5.8
199998,199998,43309,212,212109,211090,42,Doritos Corn Chip Mexican Jalapeno 150g,2,7.8
199999,199999,43374,212,212109,211091,69,Smiths Chip Thinly S/Cream&Onion 175g,2,6.0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Unnamed: 0      200000 non-null  int64
 1   Tarix           200000 non-null  int64
 2   Mağaza          200000 non-null  int64
 3   Kart_nomresi    200000 non-null  int64
 4   Transaksiya_id  200000 non-null  int64
 5   Məhsul_nomresi  200000 non-null  int64
 6   Məhsul_adi      200000 non-null  object
 7   Məhsul sayi     200000 non-null  int64
 8   Ümumi satış     200000 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 13.7+ MB

In [13]:
df.shape

(200000, 9)

In [15]:
df.isnull().sum()

Unnamed: 0        0
Tarix             0
Mağaza            0
Kart_nomresi      0
Transaksiya_id    0
Məhsul_nomresi    0
Məhsul_adi        0
Məhsul sayi       0
Ümumi satış       0
dtype: int64

In [17]:
df['Məhsul_adi']

0           Natural Chip        Compny SeaSalt175g
1                         CCs Nacho Cheese    175g
2           Smiths Crinkle Cut  Chips Chicken 170g
3           Smiths Chip Thinly  S/Cream&Onion 175g
4         Kettle Tortilla ChpsHny&Jlpno Chili 150g
                            ...
199995       Kettle Sensations   Siracha Lime 150g
199996      Natural ChipCo      Hony Soy Chckn175g
199997      Smiths Crinkle Cut  Chips Chicken 170g
199998     Doritos Corn Chip Mexican Jalapeno 150g
199999      Smiths Chip Thinly  S/Cream&Onion 175g
Name: Məhsul_adi, Length: 200000, dtype: object

In [19]:
df['Məhsul_ad'] = df['Məhsul_adi'].str.split(" ",n=1,expand=True)[0]

In [20]:
df.head()

,Unnamed: 0,Tarix,Mağaza,Kart_nomresi,Transaksiya_id,Məhsul_nomresi,Məhsul_adi,Məhsul sayi,Ümumi satış,Məhsul_ad
0,0,43390,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0,Natural
1,1,43599,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3,CCs
2,2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9,Smiths
3,3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0,Smiths
4,4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8,Kettle

In [23]:
df['Məhsul_çəki'] = df['Məhsul_adi'].str.extract("(\d+)")

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Tahir\AppData\Local\Temp\ipykernel_10636\2464299260.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Məhsul_çəki'] = df['Məhsul_adi'].str.extract("(\d+)")

In [25]:
df.head()

,Unnamed: 0,Tarix,Mağaza,Kart_nomresi,Transaksiya_id,Məhsul_nomresi,Məhsul_adi,Məhsul sayi,Ümumi satış,Məhsul_ad,Məhsul_çəki
0,0,43390,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0,Natural,175
1,1,43599,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3,CCs,175
2,2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9,Smiths,170
3,3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0,Smiths,175
4,4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8,Kettle,150

In [27]:
df['Məhsul_adi'] = df['Məhsul_adi'].str[:-4]

In [29]:
df.head()

,Unnamed: 0,Tarix,Mağaza,Kart_nomresi,Transaksiya_id,Məhsul_nomresi,Məhsul_adi,Məhsul sayi,Ümumi satış,Məhsul_ad,Məhsul_çəki
0,0,43390,1,1000,1,5,Natural Chip Compny SeaSalt,2,6.0,Natural,175
1,1,43599,1,1307,348,66,CCs Nacho Cheese,3,6.3,CCs,175
2,2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken,2,2.9,Smiths,170
3,3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion,5,15.0,Smiths,175
4,4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili,3,13.8,Kettle,150

In [31]:
df['Məhsul_adi'] = df['Məhsul_adi'].str.strip()

In [33]:
df['Məhsul_adi']

0          Natural Chip        Compny SeaSalt
1                            CCs Nacho Cheese
2           Smiths Crinkle Cut  Chips Chicken
3           Smiths Chip Thinly  S/Cream&Onion
4         Kettle Tortilla ChpsHny&Jlpno Chili
                         ...
199995       Kettle Sensations   Siracha Lime
199996     Natural ChipCo      Hony Soy Chckn
199997      Smiths Crinkle Cut  Chips Chicken
199998     Doritos Corn Chip Mexican Jalapeno
199999      Smiths Chip Thinly  S/Cream&Onion
Name: Məhsul_adi, Length: 200000, dtype: object

In [35]:
import re
df['Məhsul_adi'] = df['Məhsul_adi'].apply(lambda x: re.sub(r'\s+',' ',x).strip())

In [37]:
df['Məhsul_adi']

0                 Natural Chip Compny SeaSalt
1                            CCs Nacho Cheese
2            Smiths Crinkle Cut Chips Chicken
3            Smiths Chip Thinly S/Cream&Onion
4         Kettle Tortilla ChpsHny&Jlpno Chili
                         ...
199995         Kettle Sensations Siracha Lime
199996          Natural ChipCo Hony Soy Chckn
199997       Smiths Crinkle Cut Chips Chicken
199998     Doritos Corn Chip Mexican Jalapeno
199999       Smiths Chip Thinly S/Cream&Onion
Name: Məhsul_adi, Length: 200000, dtype: object

In [39]:
df.head()

,Unnamed: 0,Tarix,Mağaza,Kart_nomresi,Transaksiya_id,Məhsul_nomresi,Məhsul_adi,Məhsul sayi,Ümumi satış,Məhsul_ad,Məhsul_çəki
0,0,43390,1,1000,1,5,Natural Chip Compny SeaSalt,2,6.0,Natural,175
1,1,43599,1,1307,348,66,CCs Nacho Cheese,3,6.3,CCs,175
2,2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken,2,2.9,Smiths,170
3,3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion,5,15.0,Smiths,175
4,4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili,3,13.8,Kettle,150

In [41]:
df['Məhsulun_çeşidi'] = df['Məhsul_adi'].apply(lambda x: re.findall(r'\b\w+\b',x)[-1] if  isinstance(x,str) else "")

In [42]:
df.head()

,Unnamed: 0,Tarix,Mağaza,Kart_nomresi,Transaksiya_id,Məhsul_nomresi,Məhsul_adi,Məhsul sayi,Ümumi satış,Məhsul_ad,Məhsul_çəki,Məhsulun_çeşidi
0,0,43390,1,1000,1,5,Natural Chip Compny SeaSalt,2,6.0,Natural,175,SeaSalt
1,1,43599,1,1307,348,66,CCs Nacho Cheese,3,6.3,CCs,175,Cheese
2,2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken,2,2.9,Smiths,170,Chicken
3,3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion,5,15.0,Smiths,175,Onion
4,4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili,3,13.8,Kettle,150,Chili

In [45]:
df.isnull().sum()

Unnamed: 0         0
Tarix              0
Mağaza             0
Kart_nomresi       0
Transaksiya_id     0
Məhsul_nomresi     0
Məhsul_adi         0
Məhsul sayi        0
Ümumi satış        0
Məhsul_ad          0
Məhsul_çəki        0
Məhsulun_çeşidi    0
dtype: int64

In [47]:
df = df.drop(columns=['Məhsul_adi','Tarix','Transaksiya_id','Kart_nomresi'])

In [49]:
df

,Unnamed: 0,Mağaza,Məhsul_nomresi,Məhsul sayi,Ümumi satış,Məhsul_ad,Məhsul_çəki,Məhsulun_çeşidi
0,0,1,5,2,6.0,Natural,175,SeaSalt
1,1,1,66,3,6.3,CCs,175,Cheese
2,2,1,61,2,2.9,Smiths,170,Chicken
3,3,2,69,5,15.0,Smiths,175,Onion
4,4,2,108,3,13.8,Kettle,150,Chili
...,...,...,...,...,...,...,...,...
199995,199995,212,114,2,9.2,Kettle,150,Lime
199996,199996,212,106,2,6.0,Natural,175,Chckn
199997,199997,212,61,2,5.8,Smiths,170,Chicken
199998,199998,212,42,2,7.8,Doritos,150,Jalapeno
199999,199999,212,69,2,6.0,Smiths,175,Onion

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Unnamed: 0       200000 non-null  int64
 1   Mağaza           200000 non-null  int64
 2   Məhsul_nomresi   200000 non-null  int64
 3   Məhsul sayi      200000 non-null  int64
 4   Ümumi satış      200000 non-null  float64
 5   Məhsul_ad        200000 non-null  object
 6   Məhsul_çəki      200000 non-null  object
 7   Məhsulun_çeşidi  200000 non-null  object
dtypes: float64(1), int64(4), object(3)
memory usage: 12.2+ MB

In [53]:
df = df.drop(columns=['Unnamed: 0'])

In [55]:
df.head()

,Mağaza,Məhsul_nomresi,Məhsul sayi,Ümumi satış,Məhsul_ad,Məhsul_çəki,Məhsulun_çeşidi
0,1,5,2,6.0,Natural,175,SeaSalt
1,1,66,3,6.3,CCs,175,Cheese
2,1,61,2,2.9,Smiths,170,Chicken
3,2,69,5,15.0,Smiths,175,Onion
4,2,108,3,13.8,Kettle,150,Chili

In [57]:
df['Ümumi satış'] = df['Ümumi satış'].astype(float)
df['Məhsul_çəki'] = df['Məhsul_çəki'].astype(float)

In [59]:
df.dtypes

Mağaza               int64
Məhsul_nomresi       int64
Məhsul sayi          int64
Ümumi satış        float64
Məhsul_ad           object
Məhsul_çəki        float64
Məhsulun_çeşidi     object
dtype: object

In [61]:
df.isnull().sum()

Mağaza             0
Məhsul_nomresi     0
Məhsul sayi        0
Ümumi satış        0
Məhsul_ad          0
Məhsul_çəki        0
Məhsulun_çeşidi    0
dtype: int64

In [63]:
# Corellesiyani tapmaq
import seaborn as sns
import pandas as pd

correlation_matrix = df.select_dtypes(include=['number']).corr(method='pearson')
correlation_matrix

,Mağaza,Məhsul_nomresi,Məhsul sayi,Ümumi satış,Məhsul_çəki
Mağaza,1.000000,0.001647,0.003846,0.003364,0.000788
Məhsul_nomresi,0.001647,1.000000,-0.005594,-0.128625,-0.229691
Məhsul sayi,0.003846,-0.005594,1.000000,0.743634,0.009943
Ümumi satış,0.003364,-0.128625,0.743634,1.000000,0.297032
Məhsul_çəki,0.000788,-0.229691,0.009943,0.297032,1.000000

In [65]:
df.head()

,Mağaza,Məhsul_nomresi,Məhsul sayi,Ümumi satış,Məhsul_ad,Məhsul_çəki,Məhsulun_çeşidi
0,1,5,2,6.0,Natural,175.0,SeaSalt
1,1,66,3,6.3,CCs,175.0,Cheese
2,1,61,2,2.9,Smiths,170.0,Chicken
3,2,69,5,15.0,Smiths,175.0,Onion
4,2,108,3,13.8,Kettle,150.0,Chili

In [69]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.decomposition import KernelPCA
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor

# Sayısal (rəqəmsal) və kateqorial xüsusiyyətlərin seçilməsi
numeric_feature = make_column_selector(dtype_include='number')
categoric_feature = make_column_selector(dtype_include='object')

# Sayısal xüsusiyyətlər üçün pipeline
numeric_transform = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()),
])

# Kateqorial xüsusiyyətlər üçün pipeline
categoric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoding', OneHotEncoder(handle_unknown='ignore'))
])

# Sayısal və kateqorial xüsusiyyətlər üçün transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transform, numeric_feature),  
        ('cat', categoric_transformer, categoric_feature)  
    ]
)

# Model
model = GradientBoostingRegressor()

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', model)
])

In [71]:
x = df.drop(columns=['Ümumi satış'])
y = df['Ümumi satış']

In [73]:
df

,Mağaza,Məhsul_nomresi,Məhsul sayi,Ümumi satış,Məhsul_ad,Məhsul_çəki,Məhsulun_çeşidi
0,1,5,2,6.0,Natural,175.0,SeaSalt
1,1,66,3,6.3,CCs,175.0,Cheese
2,1,61,2,2.9,Smiths,170.0,Chicken
3,2,69,5,15.0,Smiths,175.0,Onion
4,2,108,3,13.8,Kettle,150.0,Chili
...,...,...,...,...,...,...,...
199995,212,114,2,9.2,Kettle,150.0,Lime
199996,212,106,2,6.0,Natural,175.0,Chckn
199997,212,61,2,5.8,Smiths,170.0,Chicken
199998,212,42,2,7.8,Doritos,150.0,Jalapeno
199999,212,69,2,6.0,Smiths,175.0,Onion

In [75]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [77]:
pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001933AF696D0>),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001933A3ED4C0>)])),
                ('model', GradientBoostingRegressor())])

In [79]:
y_pred = pipeline.predict(x_test)

In [81]:
df

,Mağaza,Məhsul_nomresi,Məhsul sayi,Ümumi satış,Məhsul_ad,Məhsul_çəki,Məhsulun_çeşidi
0,1,5,2,6.0,Natural,175.0,SeaSalt
1,1,66,3,6.3,CCs,175.0,Cheese
2,1,61,2,2.9,Smiths,170.0,Chicken
3,2,69,5,15.0,Smiths,175.0,Onion
4,2,108,3,13.8,Kettle,150.0,Chili
...,...,...,...,...,...,...,...
199995,212,114,2,9.2,Kettle,150.0,Lime
199996,212,106,2,6.0,Natural,175.0,Chckn
199997,212,61,2,5.8,Smiths,170.0,Chicken
199998,212,42,2,7.8,Doritos,150.0,Jalapeno
199999,212,69,2,6.0,Smiths,175.0,Onion

In [83]:
from sklearn.metrics import mean_squared_error,r2_score

mean_error = mean_squared_error(y_test,y_pred)
r2_scored = r2_score(y_test,y_pred)
print(mean_error)
print(r2_scored)

0.23618884480170688
0.9857501634829167

In [85]:
import pickle

In [87]:
with open('model.pkl','wb') as file:
    pickle.dump(pipeline,file)

In [285]:
df

,Mağaza,Məhsul_nomresi,Məhsul sayi,Ümumi satış,Məhsul_ad,Məhsul_çəki,Məhsulun_çeşidi
0,1,5,2,6.0,Natural,175.0,SeaSalt
1,1,66,3,6.3,CCs,175.0,Cheese
2,1,61,2,2.9,Smiths,170.0,Chicken
3,2,69,5,15.0,Smiths,175.0,Onion
4,2,108,3,13.8,Kettle,150.0,Chili
...,...,...,...,...,...,...,...
199995,212,114,2,9.2,Kettle,150.0,Lime
199996,212,106,2,6.0,Natural,175.0,Chckn
199997,212,61,2,5.8,Smiths,170.0,Chicken
199998,212,42,2,7.8,Doritos,150.0,Jalapeno
199999,212,69,2,6.0,Smiths,175.0,Onion

In [288]:
df.to_csv('new_satis.csv', index=False)

In [306]:
# df['Mağaza'].unique().tolist()

In [300]:
df['Məhsul sayi'].unique().tolist()

[2, 3, 5, 1, 4, 200]

In [296]:
df['Məhsulun_çeşidi'].unique().tolist()

['SeaSalt',
 'Cheese',
 'Chicken',
 'Onion',
 'Chili',
 'Mild',
 'Vinegar',
 'Chilli',
 'Jalapeno',
 'Chives',
 'Lime',
 'Tangy',
 'Original',
 'Rings',
 'Box',
 'Gcamole',
 'FriedChicken',
 'BBQ',
 'Mzzrlla',
 'saltd',
 'Truffle',
 'Cream',
 'Mexicana',
 'OnionDip',
 'Chckn',
 'Supreme',
 'Salsa',
 'Pesto',
 'PotatoMix',
 'Fig',
 'Seasonedchicken',
 'Crackers',
 'Jam',
 'Salted',
 'Medium',
 'Sea',
 'Burger',
 'Ht',
 'Chips',
 'Spce',
 'Med',
 'Crisps',
 'Coconut',
 'Spicy',
 'Bag',
 'Maple',
 'Salt',
 'Crips',
 'Vinegr',
 'Barbecue',
 'Puffs',
 'Ricotta',
 'Chipotle',
 'Barbeque',
 'Flavour',
 'Mstrd',
 'Balls',
 'Vingar',
 'Strws',
 'Garlic',
 'Papadums',
 'Chimuchurri',
 'Onin',
 'Sauce',
 'Pepper',
 'Aioli',
 'Belly',
 'Bolognese']